/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from 'ethers';
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from '@ethersproject/contracts';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';

interface PrintServiceV2Interface extends ethers.utils.Interface {
  functions: {
    'buy(uint256,uint256,address,uint256,bytes32)': FunctionFragment;
    'currencyConfig(uint256)': FunctionFragment;
    'orderId()': FunctionFragment;
    'owner()': FunctionFragment;
    'productConfig(uint256,uint256)': FunctionFragment;
    'renounceOwnership()': FunctionFragment;
    'setCurrencyConfig(uint256,address)': FunctionFragment;
    'setProductConfig(uint256,uint256,tuple)': FunctionFragment;
    'setTreasury(address)': FunctionFragment;
    'transferOwnership(address)': FunctionFragment;
    'treasury()': FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: 'buy',
    values: [BigNumberish, BigNumberish, string, BigNumberish, BytesLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'currencyConfig',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: 'orderId', values?: undefined): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'productConfig',
    values: [BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'setCurrencyConfig',
    values: [BigNumberish, string],
  ): string;
  encodeFunctionData(
    functionFragment: 'setProductConfig',
    values: [
      BigNumberish,
      BigNumberish,
      { id: string; price: BigNumberish; inStock: boolean },
    ],
  ): string;
  encodeFunctionData(functionFragment: 'setTreasury', values: [string]): string;
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [string],
  ): string;
  encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'currencyConfig',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'orderId', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'productConfig',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setCurrencyConfig',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setProductConfig',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setTreasury',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;

  events: {
    'OwnershipTransferred(address,address)': EventFragment;
    'PrintOrderReceived(uint256,bytes32,uint256,address,uint256)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'PrintOrderReceived'): EventFragment;
}

export class PrintServiceV2 extends Contract {
  'connect'(signerOrProvider: Signer | Provider | string): this;
  'attach'(addressOrName: string): this;
  'deployed'(): Promise<this>;

  'on'(event: EventFilter | string, listener: Listener): this;
  'once'(event: EventFilter | string, listener: Listener): this;
  'addListener'(eventName: EventFilter | string, listener: Listener): this;
  'removeAllListeners'(eventName: EventFilter | string): this;
  'removeListener'(eventName: any, listener: Listener): this;

  'interface': PrintServiceV2Interface;

  'functions': {
    buy(
      _currencyIndex: BigNumberish,
      _productIndex: BigNumberish,
      _collection: string,
      _tokenId: BigNumberish,
      _orderHash: BytesLike,
      overrides?: PayableOverrides,
    ): Promise<ContractTransaction>;

    'buy(uint256,uint256,address,uint256,bytes32)'(
      _currencyIndex: BigNumberish,
      _productIndex: BigNumberish,
      _collection: string,
      _tokenId: BigNumberish,
      _orderHash: BytesLike,
      overrides?: PayableOverrides,
    ): Promise<ContractTransaction>;

    currencyConfig(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    'currencyConfig(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[string]>;

    orderId(overrides?: CallOverrides): Promise<[BigNumber]>;

    'orderId()'(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    'owner()'(overrides?: CallOverrides): Promise<[string]>;

    productConfig(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [string, BigNumber, boolean] & {
        id: string;
        price: BigNumber;
        inStock: boolean;
      }
    >;

    'productConfig(uint256,uint256)'(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [string, BigNumber, boolean] & {
        id: string;
        price: BigNumber;
        inStock: boolean;
      }
    >;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    'renounceOwnership()'(overrides?: Overrides): Promise<ContractTransaction>;

    setCurrencyConfig(
      _currencyIndex: BigNumberish,
      _currency: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'setCurrencyConfig(uint256,address)'(
      _currencyIndex: BigNumberish,
      _currency: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    setProductConfig(
      _currencyIndex: BigNumberish,
      _productIndex: BigNumberish,
      _product: { id: string; price: BigNumberish; inStock: boolean },
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'setProductConfig(uint256,uint256,(string,uint256,bool))'(
      _currencyIndex: BigNumberish,
      _productIndex: BigNumberish,
      _product: { id: string; price: BigNumberish; inStock: boolean },
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    setTreasury(
      _treasury: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'setTreasury(address)'(
      _treasury: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    treasury(overrides?: CallOverrides): Promise<[string]>;

    'treasury()'(overrides?: CallOverrides): Promise<[string]>;
  };

  'buy'(
    _currencyIndex: BigNumberish,
    _productIndex: BigNumberish,
    _collection: string,
    _tokenId: BigNumberish,
    _orderHash: BytesLike,
    overrides?: PayableOverrides,
  ): Promise<ContractTransaction>;

  'buy(uint256,uint256,address,uint256,bytes32)'(
    _currencyIndex: BigNumberish,
    _productIndex: BigNumberish,
    _collection: string,
    _tokenId: BigNumberish,
    _orderHash: BytesLike,
    overrides?: PayableOverrides,
  ): Promise<ContractTransaction>;

  'currencyConfig'(
    arg0: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<string>;

  'currencyConfig(uint256)'(
    arg0: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<string>;

  'orderId'(overrides?: CallOverrides): Promise<BigNumber>;

  'orderId()'(overrides?: CallOverrides): Promise<BigNumber>;

  'owner'(overrides?: CallOverrides): Promise<string>;

  'owner()'(overrides?: CallOverrides): Promise<string>;

  'productConfig'(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<
    [string, BigNumber, boolean] & {
      id: string;
      price: BigNumber;
      inStock: boolean;
    }
  >;

  'productConfig(uint256,uint256)'(
    arg0: BigNumberish,
    arg1: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<
    [string, BigNumber, boolean] & {
      id: string;
      price: BigNumber;
      inStock: boolean;
    }
  >;

  'renounceOwnership'(overrides?: Overrides): Promise<ContractTransaction>;

  'renounceOwnership()'(overrides?: Overrides): Promise<ContractTransaction>;

  'setCurrencyConfig'(
    _currencyIndex: BigNumberish,
    _currency: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setCurrencyConfig(uint256,address)'(
    _currencyIndex: BigNumberish,
    _currency: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setProductConfig'(
    _currencyIndex: BigNumberish,
    _productIndex: BigNumberish,
    _product: { id: string; price: BigNumberish; inStock: boolean },
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setProductConfig(uint256,uint256,(string,uint256,bool))'(
    _currencyIndex: BigNumberish,
    _productIndex: BigNumberish,
    _product: { id: string; price: BigNumberish; inStock: boolean },
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setTreasury'(
    _treasury: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'setTreasury(address)'(
    _treasury: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'transferOwnership'(
    newOwner: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'transferOwnership(address)'(
    newOwner: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  'treasury'(overrides?: CallOverrides): Promise<string>;

  'treasury()'(overrides?: CallOverrides): Promise<string>;

  'callStatic': {
    buy(
      _currencyIndex: BigNumberish,
      _productIndex: BigNumberish,
      _collection: string,
      _tokenId: BigNumberish,
      _orderHash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<void>;

    'buy(uint256,uint256,address,uint256,bytes32)'(
      _currencyIndex: BigNumberish,
      _productIndex: BigNumberish,
      _collection: string,
      _tokenId: BigNumberish,
      _orderHash: BytesLike,
      overrides?: CallOverrides,
    ): Promise<void>;

    currencyConfig(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<string>;

    'currencyConfig(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<string>;

    orderId(overrides?: CallOverrides): Promise<BigNumber>;

    'orderId()'(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    'owner()'(overrides?: CallOverrides): Promise<string>;

    productConfig(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [string, BigNumber, boolean] & {
        id: string;
        price: BigNumber;
        inStock: boolean;
      }
    >;

    'productConfig(uint256,uint256)'(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<
      [string, BigNumber, boolean] & {
        id: string;
        price: BigNumber;
        inStock: boolean;
      }
    >;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    'renounceOwnership()'(overrides?: CallOverrides): Promise<void>;

    setCurrencyConfig(
      _currencyIndex: BigNumberish,
      _currency: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    'setCurrencyConfig(uint256,address)'(
      _currencyIndex: BigNumberish,
      _currency: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    setProductConfig(
      _currencyIndex: BigNumberish,
      _productIndex: BigNumberish,
      _product: { id: string; price: BigNumberish; inStock: boolean },
      overrides?: CallOverrides,
    ): Promise<void>;

    'setProductConfig(uint256,uint256,(string,uint256,bool))'(
      _currencyIndex: BigNumberish,
      _productIndex: BigNumberish,
      _product: { id: string; price: BigNumberish; inStock: boolean },
      overrides?: CallOverrides,
    ): Promise<void>;

    setTreasury(_treasury: string, overrides?: CallOverrides): Promise<void>;

    'setTreasury(address)'(
      _treasury: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    treasury(overrides?: CallOverrides): Promise<string>;

    'treasury()'(overrides?: CallOverrides): Promise<string>;
  };

  'filters': {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null,
    ): EventFilter;

    PrintOrderReceived(
      _orderId: BigNumberish | null,
      _orderHash: BytesLike | null,
      _productId: null,
      _collection: null,
      _tokenId: null,
    ): EventFilter;
  };

  'estimateGas': {
    buy(
      _currencyIndex: BigNumberish,
      _productIndex: BigNumberish,
      _collection: string,
      _tokenId: BigNumberish,
      _orderHash: BytesLike,
      overrides?: PayableOverrides,
    ): Promise<BigNumber>;

    'buy(uint256,uint256,address,uint256,bytes32)'(
      _currencyIndex: BigNumberish,
      _productIndex: BigNumberish,
      _collection: string,
      _tokenId: BigNumberish,
      _orderHash: BytesLike,
      overrides?: PayableOverrides,
    ): Promise<BigNumber>;

    currencyConfig(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'currencyConfig(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    orderId(overrides?: CallOverrides): Promise<BigNumber>;

    'orderId()'(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    'owner()'(overrides?: CallOverrides): Promise<BigNumber>;

    productConfig(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    'productConfig(uint256,uint256)'(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    'renounceOwnership()'(overrides?: Overrides): Promise<BigNumber>;

    setCurrencyConfig(
      _currencyIndex: BigNumberish,
      _currency: string,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    'setCurrencyConfig(uint256,address)'(
      _currencyIndex: BigNumberish,
      _currency: string,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    setProductConfig(
      _currencyIndex: BigNumberish,
      _productIndex: BigNumberish,
      _product: { id: string; price: BigNumberish; inStock: boolean },
      overrides?: Overrides,
    ): Promise<BigNumber>;

    'setProductConfig(uint256,uint256,(string,uint256,bool))'(
      _currencyIndex: BigNumberish,
      _productIndex: BigNumberish,
      _product: { id: string; price: BigNumberish; inStock: boolean },
      overrides?: Overrides,
    ): Promise<BigNumber>;

    setTreasury(_treasury: string, overrides?: Overrides): Promise<BigNumber>;

    'setTreasury(address)'(
      _treasury: string,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides,
    ): Promise<BigNumber>;

    treasury(overrides?: CallOverrides): Promise<BigNumber>;

    'treasury()'(overrides?: CallOverrides): Promise<BigNumber>;
  };

  'populateTransaction': {
    buy(
      _currencyIndex: BigNumberish,
      _productIndex: BigNumberish,
      _collection: string,
      _tokenId: BigNumberish,
      _orderHash: BytesLike,
      overrides?: PayableOverrides,
    ): Promise<PopulatedTransaction>;

    'buy(uint256,uint256,address,uint256,bytes32)'(
      _currencyIndex: BigNumberish,
      _productIndex: BigNumberish,
      _collection: string,
      _tokenId: BigNumberish,
      _orderHash: BytesLike,
      overrides?: PayableOverrides,
    ): Promise<PopulatedTransaction>;

    currencyConfig(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'currencyConfig(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    orderId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'orderId()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'owner()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    productConfig(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    'productConfig(uint256,uint256)'(
      arg0: BigNumberish,
      arg1: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    'renounceOwnership()'(overrides?: Overrides): Promise<PopulatedTransaction>;

    setCurrencyConfig(
      _currencyIndex: BigNumberish,
      _currency: string,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'setCurrencyConfig(uint256,address)'(
      _currencyIndex: BigNumberish,
      _currency: string,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    setProductConfig(
      _currencyIndex: BigNumberish,
      _productIndex: BigNumberish,
      _product: { id: string; price: BigNumberish; inStock: boolean },
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'setProductConfig(uint256,uint256,(string,uint256,bool))'(
      _currencyIndex: BigNumberish,
      _productIndex: BigNumberish,
      _product: { id: string; price: BigNumberish; inStock: boolean },
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    setTreasury(
      _treasury: string,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'setTreasury(address)'(
      _treasury: string,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides,
    ): Promise<PopulatedTransaction>;

    treasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'treasury()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
